const users = [
    { id: 1, name: "John", surname: "Doe", email: "johndoe@example.com" },
    { id: 2, name: "Jane", surname: "Doe", email: "janedoe@example.com" },
    { id: 3, name: "Bob", surname: "Smith", email: "bobsmith@example.com" },
    { id: 4, name: "Alice", surname: "Jones", email: "alicejones@example.com" },
    { id: 5, name: "David", surname: "Brown", email: "davidbrown@example.com" },
    { id: 6, name: "Emily", surname: "Davis", email: "emilydavis@example.com" },
    { id: 7, name: "Daniel", surname: "Miller", email: "danielmiller@example.com" },
    { id: 8, name: "Sophie", surname: "Wilson", email: "sophiewilson@example.com" },
    { id: 9, name: "George", surname: "Lee", email: "georgelee@example.com" },
    { id: 10, name: "Isabella", surname: "Scott", email: "isabellascott@example.com" },
    { id: 11, name: "Mason", surname: "White", email: "masonwhite@example.com" },
    { id: 12, name: "Ava", surname: "Martin", email: "avamartin@example.com" },
    { id: 13, name: "Ethan", surname: "Clark", email: "ethanclark@example.com" },
    { id: 14, name: "Olivia", surname: "Taylor", email: "oliviataylor@example.com" },
    { id: 15, name: "Liam", surname: "Adams", email: "liamadams@example.com" },
    { id: 16, name: "Chloe", surname: "Brown", email: "chloebrown@example.com" },
    { id: 17, name: "Noah", surname: "Scott", email: "noahscott@example.com" },
    { id: 18, name: "Avery", surname: "Johnson", email: "averyjohnson@example.com" },
    { id: 19, name: "Jackson", surname: "Taylor", email: "jacksontaylor@example.com" },
    { id: 20, name: "Abigail", surname: "Wilson", email: "abigailwilson@example.com" },
    { id: 21, name: "Owen", surname: "Adams", email: "owenadams@example.com" },
    { id: 22, name: "Harper", surname: "Johnson", email: "harperjohnson@example.com" },
    { id: 23, name: "Carter", surname: "Williams", email: "carterwilliams@example.com" },
    { id: 24, name: "Linda", surname: "Jackson", email: "lindajackson@example.com" },
    { id: 25, name: "Samuel", surname: "Lee", email: "samuelle@example.com" },
    { id: 26, name: "Aaliyah", surname: "Kim", email: "aaliyahkim@example.com" },
    { id: 27, name: "Adam", surname: "Garcia", email: "adamgarcia@example.com" },
    { id: 28, name: "Caroline", surname: "Nguyen", email: "carolinenguyen@example.com" },
    { id: 29, name: "Nicholas", surname: "Patel", email: "nicholaspatel@example.com" },
    { id: 30, name: "Aria", surname: "Zhang", email: "ariazhang@example.com" },
];
  
export default users;